---
title: "Prepare individual growth modelling"
author: "Sylvain Schmitt"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2:
    number_sections: false  
    toc: false
    toc_float: true
linestretch: 1.5
---

```{r setup, include=FALSE}
log_file <- file(snakemake@log[[1]], open = "wt")
sink(log_file, append = TRUE, type = "message")
sink(log_file, append = TRUE)
set.seed(42)
library(knitr)
library(tidyverse)
library(vroom)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, 
  fig.height = 6, fig.width = 8,
  cache = F, cache.lazy = F)
```

```{r snakemake, include=FALSE}
filtered <- snakemake@input[["filtered"]]
prepared <- snakemake@input[["prepared"]]
```

```{r tab}
options(knitr.kable.NA = '')
vroom(filtered) %>% 
  group_by(Family, Genus, species, idTree) %>% 
  summarise(census = n(), year_start = min(CensusYear), year_end = max(CensusYear),
            dbh_start = min(DBH), dbh_end = max(DBH)) %>% 
  ungroup() %>% 
  summarise(n_families = length(unique(Family)),
            n_genera = length(unique(Genus)),
            n_species = length(unique(species)),
            n_individuals = length(unique(idTree)),
            n_observations = nrow(vroom::vroom(filtered)),
            min_census = min(census),
            med_census = median(census),
            max_census = max(census),
            min_year0 = min(year_start),
            med_year0 = median(year_start),
            max_year0 = max(year_start),
            min_yearmax = min(year_end),
            med_yearmax = median(year_end),
            max_yearmax = max(year_end),
            min_dbh0 = min(dbh_start),
            med_dbh0 = median(dbh_start),
            max_dbh0 = max(dbh_start),
            min_dbhmax = min(dbh_end),
            med_dbhmax = median(dbh_end),
            max_dbhmax = max(dbh_end)) %>% 
  reshape2::melt() %>% 
  separate(variable, c("measure", "variable")) %>% 
  reshape2::dcast(variable ~ measure) %>% 
  dplyr::select(variable, n, med, min, max) %>% 
  mutate(variable = factor(variable, levels = c("families", "genera", "species", "individuals", "observations",
                                                "census", "year0", "yearmax", "dbh0", "dbhmax"))) %>% 
  arrange(variable) %>% 
  kable(col.names = c("", "N", "Median", "Minimum", "Maximum"), format.args = list(big.mark = " "), digits = 0,
        caption = "Metrics on inventory data used to fit the full model including sample size (N), memdian, minimum and maximum values for families, genera, species, individuals, observations, cenusus, recruitment year (year0), last censused year (yearmax), recruitment diameter (dbh0) and last censused diameter (dbhmax).")    
```

```{r fig, fig.cap="Tree diameter trajectories in reduced data. Color represent individuals."}
dplyr::select(vroom(prepared), sp, ind) %>% 
  unique() %>% 
  filter(sp %in% sample(unique(.$sp), 9, replace = T)) %>% 
  group_by(sp) %>% 
  sample_n(5, replace = T) %>%
  unique() %>% 
  left_join(vroom(prepared)) %>% 
  ggplot(aes(Year, DBH, group = as.factor(ind))) +
  geom_point(col = "grey") +
  geom_smooth(se = F, aes(col = as.factor(ind))) +
  xlim(0,NA) +
  facet_wrap(~ species, scales = "free") +
  scale_color_discrete(guide = "none")   +
  theme(strip.text = element_text(face = "italic"))
```
